=== Everspace/pso2ngstools/augment.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "$id": "PSO2NGS Capsule",
  "type": "array",
  "items": {
    "required": [
      "name",
      "category",
      "rate",
      "icon"
    ],
    "properties": {
      "name": {
        "type": "string",
        "description": "The capsule in question"
      },
      "drop": {
        "type": "string",
        "description": "Where it comes from"
      },
      "tier": {
        "type": "number",
        "description": "The I/II/II",
        "minimum": 1,
        "maximum": 6,
        "multipleOf": 1
      },
      "baseName": {
        "type": "string",
        "description": "The series the capsule is from (Precision of Precision I/II/II)"
      },
      "icon": {
        "type": "string",
        "description": "The icon to use",
        "enum": [
          "hp",
          "pp",
          "might",
          "precision",
          "technique",
          "ward",
          "special"
        ]
      },
      "category": {
        "type": "string",
        "description": "The unique category it occupies",
        "enum": [
          "soul",
          "ward",
          "basic",
          "note",
          "secreta",
          "dread",
          "gigas",
          "element"
        ]
      },
      "rate": {
        "type": "number",
        "description": "The % chance of success",
        "minimum": 1,
        "maximum": 10,
        "multipleOf": 1
      },
      "stat": {
        "type": "object",
        "properties": {
          "hp": {
            "type": "number"
          },
          "pp": {
            "type": "number"
          },
          "potency": {
            "type": "number",
            "description": "Potency +#%"
          },
          "floorPotency": {
            "type": "number",
            "description": "Potency Floor Increase +#%"
          },
          "meleePotency": {
            "type": "number"
          },
          "rangePotency": {
            "type": "number"
          },
          "techPotency": {
            "type": "number"
          },
          "damageResist": {
            "type": "number",
            "description": "Damage Resistance +/-#%"
          }
        }
      },
      "exchange": {
        "type": "object",
        "patternProperties": {
          ".*": {
            "type": "number"
          }
        }
      }
    }
  }
}

=== Everspace/pso2ngstools/src/augmenting/data/augments/dread.json
[
  {
    "name": "Dread Keeper I",
    "baseName": "Dread Keeper",
    "icon": "hp",
    "category": "dread",
    "drop": "Vetrain/Dread enemies",
    "tier": 1,
    "rate": 9,
    "stat": {
      "hp": 10,
      "pp": 3,
      "floorPotency": 1,
      "damageResist": 1
    }
  },
  {
    "name": "Dread Keeper II",
    "baseName": "Dread Keeper",
    "icon": "hp",
    "category": "dread",
    "drop": "Vetrain/Dread enemies",
    "tier": 2,
    "rate": 8,
    "stat": {
      "hp": 15,
      "pp": 4,
      "floorPotency": 1.5,
      "damageResist": 1.5
    },
    "exchange": {
      "Dread Keeper I": 10,
      "Photon Quartz": 10,
      "Dualomite": 10
    }
  }
]

=== Everspace/pso2ngstools/src/augmenting/data/augments/secreta.json
[
  {
    "name": "Alts Secreta I",
    "category": "secreta",
    "icon": "special",
    "drop": "Alters",
    "rate": 9,
    "stat": {
      "hp": -10,
      "potency": 1,
      "floorPotency": 1,
      "damageResist": -1
    }
  },
  {
    "name": "Alts Secreta II",
    "category": "secreta",
    "icon": "special",
    "drop": "Alters",
    "rate": 9,
    "stat": {
      "hp": -10,
      "potency": 1.5,
      "floorPotency": 1.5,
      "damageResist": -1.5
    },
    "exchange": {
      "Alts Secreta I": 10,
      "Photon Quartz": 10,
      "Dualomite": 10
    }
  }
]

=== Everspace/pso2ngstools/src/augmenting/data/augments/basic.json
[
  {
    "name": "Stamina I",
    "category": "basic",
    "icon": "hp",
    "tier": 1,
    "baseName": "Stamina",
    "rate": 10,
    "stat": {
      "hp": 5
    }
  },
  {
    "name": "Stamina II",
    "category": "basic",
    "icon": "hp",
    "tier": 2,
    "baseName": "Stamina",
    "rate": 10,
    "stat": {
      "hp": 10
    },
    "exchange": {
      "Stamina I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Stamina III",
    "category": "basic",
    "icon": "hp",
    "tier": 3,
    "baseName": "Stamina",
    "rate": 9,
    "stat": {
      "hp": 15
    }
  },
  {
    "name": "Spirit I",
    "category": "basic",
    "icon": "pp",
    "tier": 1,
    "baseName": "Spirit",
    "rate": 10,
    "stat": {
      "pp": 3
    }
  },
  {
    "name": "Spirit II",
    "category": "basic",
    "icon": "pp",
    "tier": 2,
    "baseName": "Spirit",
    "rate": 10,
    "stat": {
      "pp": 4
    },
    "exchange": {
      "Spirit I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Spirit III",
    "category": "basic",
    "icon": "pp",
    "tier": 3,
    "baseName": "Spirit",
    "rate": 9,
    "stat": {
      "pp": 5
    }
  },
  {
    "name": "Might I",
    "category": "basic",
    "icon": "might",
    "tier": 1,
    "baseName": "Might",
    "rate": 10,
    "stat": {
      "meleePotency": "1"
    }
  },
  {
    "name": "Might II",
    "category": "basic",
    "icon": "might",
    "tier": 2,
    "baseName": "Might",
    "rate": 10,
    "stat": {
      "meleePotency": "1.5"
    },
    "exchange": {
      "Might I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Might III",
    "category": "basic",
    "icon": "might",
    "tier": 3,
    "baseName": "Might",
    "rate": 9,
    "stat": {
      "meleePotency": "2"
    }
  },
  {
    "name": "Technique I",
    "category": "basic",
    "icon": "technique",
    "tier": 1,
    "baseName": "Technique",
    "rate": 10,
    "stat": {
      "techPotency": "1"
    }
  },
  {
    "name": "Technique II",
    "category": "basic",
    "icon": "technique",
    "tier": 2,
    "baseName": "Technique",
    "rate": 10,
    "stat": {
      "techPotency": "1.5"
    },
    "exchange": {
      "Technique I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Technique III",
    "category": "basic",
    "icon": "technique",
    "tier": 3,
    "baseName": "Technique",
    "rate": 9,
    "stat": {
      "techPotency": "2"
    }
  },
  {
    "name": "Precision I",
    "category": "basic",
    "icon": "precision",
    "tier": 1,
    "baseName": "Precision",
    "rate": 10,
    "stat": {
      "rangedPotency": "1"
    }
  },
  {
    "name": "Precision II",
    "category": "basic",
    "icon": "precision",
    "tier": 2,
    "baseName": "Precision",
    "rate": 10,
    "stat": {
      "rangedPotency": "1.5"
    },
    "exchange": {
      "Precision I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Precision III",
    "category": "basic",
    "icon": "precision",
    "tier": 3,
    "baseName": "Precision",
    "rate": 9,
    "stat": {
      "rangedPotency": "2"
    }
  },
  {
    "name": "Deftness I",
    "category": "basic",
    "icon": "special",
    "tier": 1,
    "baseName": "Deftness",
    "rate": 10,
    "stat": {
      "floorPotency": "1"
    }
  },
  {
    "name": "Deftness II",
    "category": "basic",
    "icon": "special",
    "tier": 2,
    "baseName": "Deftness",
    "rate": 10,
    "stat": {
      "floorPotency": "1.5"
    },
    "exchange": {
      "Deftness I": 10,
      "Photon Quartz": 5,
      "Monotite": 5
    }
  },
  {
    "name": "Deftness III",
    "category": "basic",
    "icon": "special",
    "tier": 3,
    "baseName": "Deftness",
    "rate": 9,
    "stat": {
      "floorPotency": "2"
    }
  },
  {
    "name": "Mastery I",
    "category": "basic",
    "icon": "special",
    "tier": 1,
    "baseName": "Mastery",
    "rate": 10,
    "stat": {
      "potency": "0.5",
      "floorPotency": "0.5",
      "damageResist": 0.5
    },
    "exchange": {
      "Might I": 5,
      "Precision I": 5,
      "Technique I": 5,
      "Photon Quartz": 5,
      "Trinite": 5
    }
  },
  {
    "name": "Mastery II",
    "category": "basic",
    "icon": "special",
    "tier": 2,
    "baseName": "Mastery",
    "rate": 10,
    "stat": {
      "potency": "1.0",
      "floorPotency": "1.0",
      "damageResist": 1.0
    },
    "exchange": {
      "Mastery I": 10,
      "Photon Quartz": 5,
      "Trinite": 5
    }
  },
  {
    "name": "Mastery III",
    "category": "basic",
    "icon": "special",
    "tier": 3,
    "baseName": "Mastery",
    "rate": 9,
    "stat": {
      "potency": "1.5",
      "floorPotency": "1.5",
      "damageResist": 0.5
    },
    "exchange": {
      "Mastery II": 10,
      "Photon Quartz": 10,
      "Trinite": 10
    }
  }
]

=== Everspace/pso2ngstools/src/augmenting/data/augments/note.json
[
  {
    "name": "Ael Note A",
    "icon": "hp",
    "category": "note",
    "drop": "Central Aelio",
    "rate": 9,
    "stat": {
      "hp": 5,
      "pp": 3
    }
  },
  {
    "name": "Ael Note B",
    "icon": "special",
    "category": "note",
    "drop": "West Aelio",
    "rate": 9,
    "stat": {
      "meleePotency": 1,
      "rangedPotency": 1
    }
  },
  {
    "name": "Ael Note C",
    "icon": "special",
    "category": "note",
    "drop": "South Aelio",
    "rate": 9,
    "stat": {
      "techPotency": 1,
      "meleePotency": 1
    }
  },
  {
    "name": "Ael Note D",
    "icon": "special",
    "category": "note",
    "drop": "North Aelio",
    "rate": 9,
    "stat": {
      "techPotency": 1,
      "rangedPotency": 1
    }
  },
  {
    "name": "Ael Domina",
    "icon": "special",
    "category": "note",
    "drop": "Central Aelio",
    "rate": 9,
    "stat": {
      "hp": 5,
      "pp": 3,
      "potency": 1.5
    }
  },
  {
    "name": "Magnus Note",
    "icon": "might",
    "category": "note",
    "drop": "Mt. Magnus",
    "rate": 9,
    "stat": {
      "meleePotency": 1.5
    }
  },
  {
    "name": "Lab Note",
    "icon": "precision",
    "category": "note",
    "drop": "Vanford Laboratory Ruins",
    "rate": 9,
    "stat": {
      "rangedPotency": 1.5
    }
  },
  {
    "name": "Resola Note",
    "icon": "technique",
    "category": "note",
    "drop": "Resola Forest",
    "rate": 9,
    "stat": {
      "techPotency": 1.5
    }
  }
]

=== Everspace/pso2ngstools/src/augmenting/data/augments/gigas.json
[
  {
    "name": "Gigas Might I",
    "baseName": "Gigas Might",
    "icon": "might",
    "tier": 1,
    "category": "gigas",
    "rate": 9,
    "stat": {
      "hp": 5,
      "meleePotency": 1.5
    }
  },
  {
    "name": "Gigas Might II",
    "icon": "might",
    "baseName": "Gigas Might",
    "tier": 2,
    "category": "gigas",
    "rate": 8,
    "stat": {
      "hp": 10,
      "meleePotency": 2
    },
    "exchange": {
      "Gigas Might I": 10,
      "Photon Quartz": 10,
      "Dualomite": 10
    }
  },
  {
    "name": "Gigas Precision I",
    "category": "gigas",
    "baseName": "Gigas Precision",
    "icon": "precision",
    "tier": 1,
    "rate": 9,
    "stat": {
      "hp": 5,
      "rangePotency": 1.5
    }
  },
  {
    "name": "Gigas Precision II",
    "category": "gigas",
    "baseName": "Gigas Precision",
    "icon": "precision",
    "tier": 2,
    "rate": 8,
    "stat": {
      "hp": 10,
      "rangePotency": 2
    },
    "exchange": {
      "Gigas Precision I": 10,
      "Photon Quartz": 10,
      "Dualomite": 10
    }
  },
  {
    "name": "Gigas Technique I",
    "category": "gigas",
    "baseName": "Gigas Technique",
    "icon": "technique",
    "tier": 1,
    "rate": 9,
    "stat": {
      "hp": 5,
      "techPotency": 1.5
    }
  },
  {
    "name": "Gigas Technique II",
    "category": "gigas",
    "baseName": "Gigas Technique",
    "icon": "technique",
    "tier": 2,
    "rate": 8,
    "stat": {
      "hp": 10,
      "techPotency": 2
    },
    "exchange": {
      "Gigas Technique I": 10,
      "Photon Quartz": 10,
      "Dualomite": 10
    }
  }
]
